---
- name: "Enabling linger for {{ heco_user_name }}"
  command: "loginctl enable-linger {{ heco_user_name }}"

- name: "Finding uid of {{ heco_user_name }}"
  command: "id -u {{ heco_user_name }}"
  register: the_user_uid
  check_mode: no
  changed_when: false
  become: true
  become_user: "{{ heco_user_name }}"

- name: "Determining XDG_RUNTIME_DIR"
  set_fact:
    xdg_runtime_dir: "/run/user/{{ the_user_uid.stdout }}"
  changed_when: false
  become: true
  become_user: "{{ heco_user_name }}"

- name: "Updating bashrc for {{ heco_user_name }}"
  lineinfile:
    path: "/home/{{ heco_user_name }}/.bashrc"
    line: "export XDG_RUNTIME_DIR=/run/user/{{ the_user_uid.stdout }}"
  
- name: "Creating {{ heco_sevice_name }} systemd service"
  template:
    src: heco.service.j2
    dest: "{{ heco_service_dir }}/{{ heco_sevice_name }}.service"
    mode: 0644

- name: "Applying {{ heco_sevice_name }} Service Parameters"
  become: true
  become_user: "{{ heco_user_name }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    scope: user
    daemon_reload: yes
    name: "{{ heco_sevice_name }}.service"
    enabled: "{{ heco_service_enabled }}"
    state: "{{ heco_service_state }}"
